[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "random-walk-microstructures"
version = "1.0.0"
description = "This repository contains the code for our ACM SCF 2025 paper \"Random-Walk Microstructures for Differentiable Topology Optimization.\""
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [
  { name = "Samuel Silverman et al." },
]
maintainers = [
  { name = "Samuel Silverman", email = "sssilver@bu.edu" },
]
dependencies = [
  "matplotlib==3.9.2",
  "numpy==1.26.4",
  "scikit-image==0.24.0",
  "scikit-learn==1.5.2",
  "torch==2.2.2",
  "tqdm==4.68.2",
  "triangle==20230923",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
